# Generated by Django 5.2.6 on 2025-09-11 15:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PirateQueen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('historical_period', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pirate_name', models.CharField(help_text='Your captain name', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='Tell us about your pirate adventures', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_difficulty', models.CharField(choices=[('easy', 'Easy (15 shots)'), ('normal', 'Normal (10 shots)'), ('hard', 'Hard (7 shots)')], default='normal', max_length=20)),
                ('chosen_pirate_queen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pirates.piratequeen')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('win', 'Victory'), ('loss', 'Defeat')], max_length=10)),
                ('shots_fired', models.IntegerField()),
                ('ships_sunk', models.IntegerField()),
                ('total_ships', models.IntegerField(default=5)),
                ('difficulty', models.CharField(default='normal', max_length=20)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('played_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pirates.userprofile')),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
    ]
