# Generated by Django 4.2.9 on 2025-09-30 16:29
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ('pirates', '0001_initial'),
    ]
    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_difficulty',
            field=models.CharField(
                choices=[
                    ('easy', 'Easy (25 shots)'),
                    ('normal', 'Normal (20 shots)'),
                    ('hard', 'Hard (15 shots)')
                ],
                default='normal',
                max_length=20
            ),
        ),
    ]
